# Generated by Django 4.0.2 on 2022-02-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30)),
                ('role_description', models.TextField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orm.role')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
                ('user_phone', models.CharField(max_length=30)),
                ('user_address', models.TextField(max_length=30)),
                ('user_dob', models.DateField(max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
            bases=('orm.role',),
        ),
    ]
