# Generated by Django 4.0.2 on 2022-02-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orm.role')),
                ('employyee_name', models.CharField(max_length=30)),
                ('employyee_email', models.CharField(max_length=30)),
                ('employyee_password', models.CharField(max_length=30)),
                ('employyee_phone', models.CharField(max_length=30)),
                ('employyee_address', models.TextField(max_length=30)),
                ('employyee_dob', models.DateField(max_length=30)),
            ],
            options={
                'db_table': 'employee',
            },
            bases=('orm.role',),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
