# Generated by Django 4.0.2 on 2022-02-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_customer_product_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
