# Generated by Django 4.0.2 on 2022-02-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_details',
        ),
    ]
