# Generated by Django 4.0.2 on 2022-02-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_project_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_color',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
