# Generated by Django 4.0.2 on 2022-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
